### PR TITLE
ui: initial sidebar and logo

### LINKED ISSUE #704: Add Bloom logo to Bloom UI

### PR DESCRIPTION
**Pull request by Tuditi**
## Summary

closes: https://github.com/bloomwalletio/bloom/issues/704

Creates Sidebar with new logo and larger width. 
Use the new icon set for the sidebar icons

...

### Platforms

> Please select any platforms where your changes have been tested.

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [ ] Windows

### Instructions

> Please describe the specific instructions, configurations, and/or test cases necessary to **test and verify** that your changes work as intended.

...

## Checklist

> Please tick the following boxes that are relevant to your changes.

-   [ ] I have followed the contribution guidelines for this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [ ] I have verified that new and existing unit tests pass locally with my changes
-   [ ] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by maxwellmattryan** [comment]
Everything is looking good, but I'm getting this error right after logging in:
Screenshot from 2023-09-15 16-14-54

I tried re-building and that didn't seem to help :thinking:

**Review by maxwellmattryan — CHANGES_REQUESTED** [review]
Code and UI look good, see comment above ^

**Comment by Tuditi** [comment]
> Code and UI look good, see comment above ^

The problem you're experiencing is due to the fact that I'm using a new logo that needs a new bloom ui kit release (I was using `bloom-ui-kit/develop` when developing. I'll release a new version and I'll update this PR.

**Review by maxwellmattryan — APPROVED** [review]
LGTM :cherry_blossom:

**Pull request merged**
