### PR TITLE
fix: system theme

### LINKED ISSUE #1439: Fix system theme

### PR DESCRIPTION
**Pull request by jeeanribeiro**
## Summary

This fixes the reactivity of theme setting by creating an `appSettings` store subscriber that uses the `nativeTheme` Electron API to update the theme and updates the darkMode store by relying on `nativeTheme.shouldUseDarkColors` because it already has the correct logic for `dark|light|system`.

### Platforms

-   **Desktop**
    -   [ ] MacOS
    -   [ ] Linux
    -   [x] Windows

### Instructions

- Switch between the three different theme settings and check the elements on the screen (mainly the logo on the top-left)

## Checklist

-   [x] I have followed the contribution guidelines for this project
-   [x] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added or modified tests that prove my changes work as intended
-   [x] I have verified that new and existing unit tests pass locally with my changes
-   [x] I have verified that my latest changes pass CI workflows for testing and linting
-   [ ] I have made corresponding changes to the documentation

### CODE REVIEW

**Review by nicole-obrien — DISMISSED** [review]
When starting app in system theme the darmode prop is false by default but updates after changing theme

**Comment by MarkNerdi** [comment]
Also if i switch theme, the Bloom icon isnt updated. Only after restarting the app, the corresponding logo is rendered

**Comment by nicole-obrien** [comment]
> Also if i switch theme, the Bloom icon isnt updated. Only after restarting the app, the corresponding logo is rendered

Opposite happens for me

**Review by Tuditi — APPROVED** [review]
LGTM! :fire:

**Review by MarkNerdi — APPROVED** [review]
LGTM 2

**Pull request merged**
